FROM golang:1.25.0

RUN apt-get update && apt-get install -y ca-certificates -y \
    git \
    curl \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY .env .env 
ENV $(cat .env | xargs )

EXPOSE 8080

CMD ["air"]   