// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GenderTypes string

const (
	GenderTypesMale   GenderTypes = "male"
	GenderTypesFemale GenderTypes = "female"
	GenderTypesOther  GenderTypes = "other"
)

func (e *GenderTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderTypes(s)
	case string:
		*e = GenderTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderTypes: %T", src)
	}
	return nil
}

type NullGenderTypes struct {
	GenderTypes GenderTypes `json:"gender_types"`
	Valid       bool        `json:"valid"` // Valid is true if GenderTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderTypes) Scan(value interface{}) error {
	if value == nil {
		ns.GenderTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderTypes), nil
}

type Tester struct {
	ID          uuid.UUID        `json:"id"`
	Email       string           `json:"email"`
	FirstName   string           `json:"first_name"`
	LastName    string           `json:"last_name"`
	PhoneNumber *string          `json:"phone_number"`
	IsVerified  bool             `json:"is_verified"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	FirstName    string           `json:"first_name"`
	LastName     string           `json:"last_name"`
	PasswordHash string           `json:"password_hash"`
	Gender       NullGenderTypes  `json:"gender"`
	PhoneNumber  *string          `json:"phone_number"`
	IsVerified   bool             `json:"is_verified"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
