// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	UpdateGender(ctx context.Context, arg UpdateGenderParams) error
	UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error
}

var _ Querier = (*Queries)(nil)
