// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, first_name, last_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
}

type CreateUserRow struct {
	ID        uuid.UUID        `json:"id"`
	Email     string           `json:"email"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_verified, first_name, last_name
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	IsVerified   bool      `json:"is_verified"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, is_verified, first_name, last_name
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	IsVerified bool      `json:"is_verified"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsVerified,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateGender = `-- name: UpdateGender :exec
UPDATE users
SET gender = $1, updated_at = now()
WHERE id = $2
`

type UpdateGenderParams struct {
	Gender NullGenderTypes `json:"gender"`
	ID     uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateGender(ctx context.Context, arg UpdateGenderParams) error {
	_, err := q.db.Exec(ctx, updateGender, arg.Gender, arg.ID)
	return err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
UPDATE users
SET phone_number = $1, updated_at = now()
WHERE id = $2
`

type UpdatePhoneNumberParams struct {
	PhoneNumber *string   `json:"phone_number"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updatePhoneNumber, arg.PhoneNumber, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserVerified = `-- name: UpdateUserVerified :exec
UPDATE users
SET is_verified = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserVerifiedParams struct {
	IsVerified bool      `json:"is_verified"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserVerified, arg.IsVerified, arg.ID)
	return err
}
